// 영어 엔진 커리큘럼 — 단일 소스. 앱(index.html)과 음성 생성기(generate_audio.py)가 함께 읽는다.
// 규칙: 이 객체 안에는 // 주석 금지(엄격 JSON으로 파싱됨). 주석은 이 윗부분에만.
// items[].id = 음성파일 이름(audio/<id>_ko.mp3 / _en.mp3). 개념 음성 = audio/d<day>_intro.mp3
window.CURRICULUM = {
  "trip": { "name": "칸쿤 동굴 다이빙", "start": "2026-07-13" },
  "days": [
    {
      "day": 1, "verb": "be", "phase": "뼈대", "ready": true, "title": "be · 나는 ~이야",
      "concept": "오늘은 동사 하나, be. 한국어로 ~야, ~이다, ~한 상태야를 영어는 전부 be 하나로 말해. I'm 나는, You're 너는, It's 그건 에다 단어 하나만 붙이면 끝. I'm okay. I'm ready. I'm hungry. 어렵게 갈 거 없어. 오늘은 이 한 동사로 기분과 상태, 어디 있는지까지 다 말해본다.",
      "items": [
        { "id": "d1_01", "tag": "be", "ko": "나 괜찮아.", "en": "I'm okay." },
        { "id": "d1_02", "tag": "be", "ko": "너 괜찮아?", "en": "Are you okay?" },
        { "id": "d1_03", "tag": "be", "ko": "나 준비됐어.", "en": "I'm ready." },
        { "id": "d1_04", "tag": "be", "ko": "너 준비됐어?", "en": "Are you ready?" },
        { "id": "d1_05", "tag": "be", "ko": "나 배고파.", "en": "I'm hungry." },
        { "id": "d1_06", "tag": "be", "ko": "나 피곤해.", "en": "I'm tired." },
        { "id": "d1_07", "tag": "be", "ko": "나 여기 있어.", "en": "I'm here." },
        { "id": "d1_08", "tag": "be", "ko": "너 어디야?", "en": "Where are you?" },
        { "id": "d1_09", "tag": "be", "ko": "이거 좋다.", "en": "This is good." },
        { "id": "d1_10", "tag": "be", "ko": "그거 괜찮아.", "en": "It's okay." },
        { "id": "d1_11", "tag": "be", "ko": "너무 추워.", "en": "It's too cold." },
        { "id": "d1_12", "tag": "be", "ko": "나 안 괜찮아.", "en": "I'm not okay." },
        { "id": "d1_13", "tag": "be", "ko": "나 행복해.", "en": "I'm happy." },
        { "id": "d1_14", "tag": "be", "ko": "그거 쉬워.", "en": "It's easy." },
        { "id": "d1_15", "tag": "be", "ko": "이거 어려워.", "en": "This is hard." },
        { "id": "d1_16", "tag": "be", "ko": "너 늦었어.", "en": "You're late." },
        { "id": "d1_17", "tag": "be", "ko": "나 안 바빠.", "en": "I'm not busy." },
        { "id": "d1_18", "tag": "be", "ko": "그 사람 친절해.", "en": "He's nice." },
        { "id": "d1_19", "tag": "be", "ko": "우리 친구야.", "en": "We're friends." },
        { "id": "d1_20", "tag": "be", "ko": "맞아.", "en": "That's right." }
      ]
    },
    {
      "day": 2, "verb": "be", "phase": "뼈대", "ready": true, "title": "be · 어디야 / ~ 아니야",
      "concept": "같은 be로 어디 있는지, 아니야, 이건 저건을 말한다. I'm at home. It's there. This is mine. Where is...? 여행에서 제일 많이 쓸 화장실 어디예요도 여기서 나와.",
      "items": [
        { "id": "d2_01", "tag": "be", "ko": "나 집에 있어.", "en": "I'm at home." },
        { "id": "d2_02", "tag": "be", "ko": "나 직장에 있어.", "en": "I'm at work." },
        { "id": "d2_03", "tag": "be", "ko": "그거 여기 있어.", "en": "It's here." },
        { "id": "d2_04", "tag": "be", "ko": "그거 저기 있어.", "en": "It's there." },
        { "id": "d2_05", "tag": "be", "ko": "나 안에 있어.", "en": "I'm inside." },
        { "id": "d2_06", "tag": "be", "ko": "나 밖에 있어.", "en": "I'm outside." },
        { "id": "d2_07", "tag": "be", "ko": "이건 내 거야.", "en": "This is mine." },
        { "id": "d2_08", "tag": "be", "ko": "그건 네 거야.", "en": "That's yours." },
        { "id": "d2_09", "tag": "be", "ko": "이게 뭐야?", "en": "What is this?" },
        { "id": "d2_10", "tag": "be", "ko": "그건 안 좋아.", "en": "That's not good." },
        { "id": "d2_11", "tag": "be", "ko": "나 늦지 않았어.", "en": "I'm not late." },
        { "id": "d2_12", "tag": "be", "ko": "우리 거의 다 왔어.", "en": "We're almost there." },
        { "id": "d2_13", "tag": "be", "ko": "그 사람 여기 없어.", "en": "He's not here." },
        { "id": "d2_14", "tag": "be", "ko": "화장실 어디예요?", "en": "Where is the bathroom?" },
        { "id": "d2_15", "tag": "be", "ko": "내 가방 어디 있어?", "en": "Where is my bag?" },
        { "id": "d2_16", "tag": "be", "ko": "그거 멀어?", "en": "Is it far?" },
        { "id": "d2_17", "tag": "be", "ko": "그거 가까워.", "en": "It's close." },
        { "id": "d2_18", "tag": "be", "ko": "우리 준비됐어.", "en": "We're ready." },
        { "id": "d2_19", "tag": "be", "ko": "너 거기 있어?", "en": "Are you there?" },
        { "id": "d2_20", "tag": "be", "ko": "그 사람 누구야?", "en": "Who is he?" }
      ]
    },
    {
      "day": 3, "verb": "have", "phase": "뼈대", "ready": true, "title": "have · 가지다",
      "concept": "have는 있다. 가진 것, 그리고 너 ~ 있어?. I have a car. Do you have time? I don't have money. 여행에서 I have a reservation 예약 있어요 까지 다 이거 하나로.",
      "items": [
        { "id": "d3_01", "tag": "have", "ko": "나 차 있어.", "en": "I have a car." },
        { "id": "d3_02", "tag": "have", "ko": "나 시간 있어.", "en": "I have time." },
        { "id": "d3_03", "tag": "have", "ko": "나 시간 없어.", "en": "I don't have time." },
        { "id": "d3_04", "tag": "have", "ko": "너 시간 있어?", "en": "Do you have time?" },
        { "id": "d3_05", "tag": "have", "ko": "나 질문 있어.", "en": "I have a question." },
        { "id": "d3_06", "tag": "have", "ko": "나 돈 없어.", "en": "I don't have money." },
        { "id": "d3_07", "tag": "have", "ko": "너 펜 있어?", "en": "Do you have a pen?" },
        { "id": "d3_08", "tag": "have", "ko": "나 형제 있어.", "en": "I have a brother." },
        { "id": "d3_09", "tag": "have", "ko": "나 강아지 있어.", "en": "I have a dog." },
        { "id": "d3_10", "tag": "have", "ko": "우리 문제 있어.", "en": "We have a problem." },
        { "id": "d3_11", "tag": "have", "ko": "나 좋은 생각 있어.", "en": "I have an idea." },
        { "id": "d3_12", "tag": "have", "ko": "너 여권 있어?", "en": "Do you have your passport?" },
        { "id": "d3_13", "tag": "have", "ko": "나 예약 있어.", "en": "I have a reservation." },
        { "id": "d3_14", "tag": "have", "ko": "나 표 있어.", "en": "I have a ticket." },
        { "id": "d3_15", "tag": "have", "ko": "너 현금 있어?", "en": "Do you have cash?" },
        { "id": "d3_16", "tag": "have", "ko": "나 아무것도 없어.", "en": "I don't have anything." },
        { "id": "d3_17", "tag": "have", "ko": "그 사람 차 있어.", "en": "He has a car." },
        { "id": "d3_18", "tag": "have", "ko": "너 와이파이 있어요?", "en": "Do you have wifi?" },
        { "id": "d3_19", "tag": "have", "ko": "나 5분 있어.", "en": "I have five minutes." },
        { "id": "d3_20", "tag": "have", "ko": "방 있어요?", "en": "Do you have a room?" }
      ]
    },
    {
      "day": 4, "verb": "have", "phase": "뼈대", "ready": true, "title": "have · 먹다·해야 해",
      "concept": "have의 다른 얼굴. have lunch는 점심을 먹는다는 뜻 — have가 곧 먹다야. have a good time은 좋은 시간을 보내다. have to는 해야 한다. 한 동사로 식사·경험·의무를 다 말해.",
      "items": [
        { "id": "d4_01", "tag": "have", "ko": "나 점심 먹어.", "en": "I have lunch." },
        { "id": "d4_02", "tag": "have", "ko": "나 아침 먹었어.", "en": "I had breakfast." },
        { "id": "d4_03", "tag": "have", "ko": "나 매일 커피 마셔.", "en": "I have coffee every day." },
        { "id": "d4_04", "tag": "have", "ko": "우리 7시에 저녁 먹어.", "en": "We have dinner at seven." },
        { "id": "d4_05", "tag": "have", "ko": "좋은 시간 보내.", "en": "Have a good time." },
        { "id": "d4_06", "tag": "have", "ko": "좋은 하루 보내.", "en": "Have a good day." },
        { "id": "d4_07", "tag": "have", "ko": "나 가야 해.", "en": "I have to go." },
        { "id": "d4_08", "tag": "have", "ko": "나 일해야 해.", "en": "I have to work." },
        { "id": "d4_09", "tag": "have", "ko": "너 가야 해?", "en": "Do you have to go?" },
        { "id": "d4_10", "tag": "have", "ko": "나 지금 가야 해.", "en": "I have to go now." },
        { "id": "d4_11", "tag": "have", "ko": "우리 기다려야 해.", "en": "We have to wait." },
        { "id": "d4_12", "tag": "have", "ko": "나 안 가도 돼.", "en": "I don't have to go." },
        { "id": "d4_13", "tag": "have", "ko": "나 회의 있어.", "en": "I have a meeting." },
        { "id": "d4_14", "tag": "have", "ko": "나 좋은 시간 보냈어.", "en": "I had a good time." },
        { "id": "d4_15", "tag": "have", "ko": "재밌게 놀아.", "en": "Have fun." },
        { "id": "d4_16", "tag": "have", "ko": "나 감기 걸렸어.", "en": "I have a cold." },
        { "id": "d4_17", "tag": "have", "ko": "나 두통 있어.", "en": "I have a headache." },
        { "id": "d4_18", "tag": "have", "ko": "너 이거 봐야 해.", "en": "You have to see this." },
        { "id": "d4_19", "tag": "have", "ko": "나 자야 해.", "en": "I have to sleep." },
        { "id": "d4_20", "tag": "have", "ko": "우리 서둘러야 해.", "en": "We have to hurry." }
      ]
    },
    {
      "day": 5, "verb": "do", "phase": "뼈대", "ready": true, "title": "do · 질문·부정 엔진",
      "concept": "do는 질문과 부정을 만드는 엔진이야. Do you...? 로 묻고, I don't... 로 부정해. 어려운 문법 없이 do 하나면 묻고 아니라고 말할 수 있어. Don't worry 걱정 마처럼 명령에도 써.",
      "items": [
        { "id": "d5_01", "tag": "do", "ko": "나 몰라.", "en": "I don't know." },
        { "id": "d5_02", "tag": "do", "ko": "너 알아?", "en": "Do you know?" },
        { "id": "d5_03", "tag": "do", "ko": "나 안 좋아해.", "en": "I don't like it." },
        { "id": "d5_04", "tag": "do", "ko": "너 이거 좋아해?", "en": "Do you like this?" },
        { "id": "d5_05", "tag": "do", "ko": "너 영어 할 줄 알아?", "en": "Do you speak English?" },
        { "id": "d5_06", "tag": "do", "ko": "나 이해 안 돼.", "en": "I don't understand." },
        { "id": "d5_07", "tag": "do", "ko": "너 이해돼?", "en": "Do you understand?" },
        { "id": "d5_08", "tag": "do", "ko": "나 신경 안 써.", "en": "I don't care." },
        { "id": "d5_09", "tag": "do", "ko": "너 무슨 일 해?", "en": "What do you do?" },
        { "id": "d5_10", "tag": "do", "ko": "이거 어떻게 해?", "en": "How do you do it?" },
        { "id": "d5_11", "tag": "do", "ko": "나 커피 안 마셔.", "en": "I don't drink coffee." },
        { "id": "d5_12", "tag": "do", "ko": "너 커피 마셔?", "en": "Do you drink coffee?" },
        { "id": "d5_13", "tag": "do", "ko": "나 담배 안 피워.", "en": "I don't smoke." },
        { "id": "d5_14", "tag": "do", "ko": "너 운전해?", "en": "Do you drive?" },
        { "id": "d5_15", "tag": "do", "ko": "나 운동 잘 안 해.", "en": "I don't exercise much." },
        { "id": "d5_16", "tag": "do", "ko": "너 날 알아?", "en": "Do you know me?" },
        { "id": "d5_17", "tag": "do", "ko": "나 그거 안 했어.", "en": "I didn't do it." },
        { "id": "d5_18", "tag": "do", "ko": "너 그거 했어?", "en": "Did you do it?" },
        { "id": "d5_19", "tag": "do", "ko": "걱정 마.", "en": "Don't worry." },
        { "id": "d5_20", "tag": "do", "ko": "서두르지 마.", "en": "Don't rush." }
      ]
    },
    {
      "day": 6, "verb": "복습", "phase": "뼈대", "ready": true, "title": "복습 · be+have+do",
      "concept": "오늘은 복습. be·have·do 세 동사를 and, so, but, because로 이어 첫 대화를 만든다. 짧은 문장 두 개를 붙이면 그게 대화야.",
      "items": [
        { "id": "d6_01", "tag": "mix", "ko": "나 배고파, 뭐 좀 먹어야 해.", "en": "I'm hungry, so I have to eat." },
        { "id": "d6_02", "tag": "mix", "ko": "시간 없어, 가야 해.", "en": "I don't have time, so I have to go." },
        { "id": "d6_03", "tag": "mix", "ko": "나 몰라. 너 알아?", "en": "I don't know. Do you know?" },
        { "id": "d6_04", "tag": "mix", "ko": "나 피곤해, 자야 해.", "en": "I'm tired, so I have to sleep." },
        { "id": "d6_05", "tag": "mix", "ko": "나 차 있는데 시간이 없어.", "en": "I have a car, but I don't have time." },
        { "id": "d6_06", "tag": "mix", "ko": "너 준비됐어? 가야 해.", "en": "Are you ready? We have to go." },
        { "id": "d6_07", "tag": "mix", "ko": "나 질문 있어.", "en": "I have a question." },
        { "id": "d6_08", "tag": "mix", "ko": "별로야. 다른 거 있어?", "en": "It's not good. Do you have another one?" },
        { "id": "d6_09", "tag": "mix", "ko": "나 안 바빠, 시간 있어.", "en": "I'm not busy. I have time." },
        { "id": "d6_10", "tag": "mix", "ko": "너 영어 해? 나 한국어 해.", "en": "Do you speak English? I speak Korean." },
        { "id": "d6_11", "tag": "mix", "ko": "나 이해 안 돼. 너 이해돼?", "en": "I don't understand. Do you understand?" },
        { "id": "d6_12", "tag": "mix", "ko": "우리 늦었어, 서둘러야 해.", "en": "We're late, so we have to hurry." },
        { "id": "d6_13", "tag": "mix", "ko": "나 괜찮아, 걱정 마.", "en": "I'm okay. Don't worry." },
        { "id": "d6_14", "tag": "mix", "ko": "너 시간 있어? 나 질문 있어.", "en": "Do you have time? I have a question." },
        { "id": "d6_15", "tag": "mix", "ko": "나 배 안 고파, 점심 먹었어.", "en": "I'm not hungry. I had lunch." },
        { "id": "d6_16", "tag": "mix", "ko": "그 사람 차 있는데 운전 안 해.", "en": "He has a car, but he doesn't drive." },
        { "id": "d6_17", "tag": "mix", "ko": "좋은 하루 보내.", "en": "Have a good day." },
        { "id": "d6_18", "tag": "mix", "ko": "나 그거 했어. 너도 했어?", "en": "I did it. Did you do it?" },
        { "id": "d6_19", "tag": "mix", "ko": "우리 문제 있어.", "en": "We have a problem." },
        { "id": "d6_20", "tag": "mix", "ko": "나 가야 해, 일 있어.", "en": "I have to go. I have work." }
      ]
    },
    {
      "day": 7, "verb": "go", "phase": "이동·만능", "ready": true, "title": "go · 가다",
      "concept": "go는 가다. 지금 가는 중은 be going이야. I'm going home. Where are you going? 어디로 가는지를 이 한 동사로 다 말해.",
      "items": [
        { "id": "d7_01", "tag": "go", "ko": "나 집에 가.", "en": "I'm going home." },
        { "id": "d7_02", "tag": "go", "ko": "나 일하러 가.", "en": "I'm going to work." },
        { "id": "d7_03", "tag": "go", "ko": "너 어디 가?", "en": "Where are you going?" },
        { "id": "d7_04", "tag": "go", "ko": "우리 지금 가.", "en": "We're going now." },
        { "id": "d7_05", "tag": "go", "ko": "나 안 가.", "en": "I'm not going." },
        { "id": "d7_06", "tag": "go", "ko": "너 가?", "en": "Are you going?" },
        { "id": "d7_07", "tag": "go", "ko": "나 학교 가.", "en": "I'm going to school." },
        { "id": "d7_08", "tag": "go", "ko": "그 사람 집에 가.", "en": "He's going home." },
        { "id": "d7_09", "tag": "go", "ko": "우리 같이 가.", "en": "We're going together." },
        { "id": "d7_10", "tag": "go", "ko": "나 거기 가.", "en": "I'm going there." },
        { "id": "d7_11", "tag": "go", "ko": "나 이제 가.", "en": "I'm going now." },
        { "id": "d7_12", "tag": "go", "ko": "나 화장실 가.", "en": "I'm going to the bathroom." },
        { "id": "d7_13", "tag": "go", "ko": "너 시내 가?", "en": "Are you going downtown?" },
        { "id": "d7_14", "tag": "go", "ko": "우리 늦어, 가야 해.", "en": "We're late. We have to go." },
        { "id": "d7_15", "tag": "go", "ko": "나 안 가, 피곤해.", "en": "I'm not going. I'm tired." },
        { "id": "d7_16", "tag": "go", "ko": "이 버스 시내 가요?", "en": "Does this bus go downtown?" },
        { "id": "d7_17", "tag": "go", "ko": "이 길 해변으로 가요?", "en": "Does this road go to the beach?" },
        { "id": "d7_18", "tag": "go", "ko": "너 지금 가?", "en": "Are you going now?" },
        { "id": "d7_19", "tag": "go", "ko": "나 곧 가.", "en": "I'm going soon." },
        { "id": "d7_20", "tag": "go", "ko": "그 사람들 해변 가.", "en": "They're going to the beach." }
      ]
    },
    {
      "day": 8, "verb": "go", "phase": "이동·만능", "ready": true, "title": "go · ~할 거야",
      "concept": "go에 to를 붙이면 미래. going to는 앞으로 할 일이야. I'm going to eat. What are you going to do? 어려운 미래 시제 필요 없어, 전부 going to로.",
      "items": [
        { "id": "d8_01", "tag": "go", "ko": "나 먹을 거야.", "en": "I'm going to eat." },
        { "id": "d8_02", "tag": "go", "ko": "너 뭐 할 거야?", "en": "What are you going to do?" },
        { "id": "d8_03", "tag": "go", "ko": "나 잘 거야.", "en": "I'm going to sleep." },
        { "id": "d8_04", "tag": "go", "ko": "우리 늦을 거야.", "en": "We're going to be late." },
        { "id": "d8_05", "tag": "go", "ko": "나 그 사람한테 물어볼 거야.", "en": "I'm going to ask him." },
        { "id": "d8_06", "tag": "go", "ko": "너 그거 살 거야?", "en": "Are you going to buy it?" },
        { "id": "d8_07", "tag": "go", "ko": "나 안 갈 거야.", "en": "I'm not going to go." },
        { "id": "d8_08", "tag": "go", "ko": "비 올 거야.", "en": "It's going to rain." },
        { "id": "d8_09", "tag": "go", "ko": "나 기다릴 거야.", "en": "I'm going to wait." },
        { "id": "d8_10", "tag": "go", "ko": "우리 다이빙할 거야.", "en": "We're going to dive." },
        { "id": "d8_11", "tag": "go", "ko": "너 어디 갈 거야?", "en": "Where are you going to go?" },
        { "id": "d8_12", "tag": "go", "ko": "나 그거 해볼 거야.", "en": "I'm going to try it." },
        { "id": "d8_13", "tag": "go", "ko": "그 사람 올 거야.", "en": "He's going to come." },
        { "id": "d8_14", "tag": "go", "ko": "나 쉴 거야.", "en": "I'm going to rest." },
        { "id": "d8_15", "tag": "go", "ko": "너 도와줄 거야?", "en": "Are you going to help?" },
        { "id": "d8_16", "tag": "go", "ko": "나 집에 있을 거야.", "en": "I'm going to stay home." },
        { "id": "d8_17", "tag": "go", "ko": "우리 괜찮을 거야.", "en": "We're going to be okay." },
        { "id": "d8_18", "tag": "go", "ko": "나 나중에 전화할 거야.", "en": "I'm going to call you later." },
        { "id": "d8_19", "tag": "go", "ko": "너 언제 갈 거야?", "en": "When are you going to go?" },
        { "id": "d8_20", "tag": "go", "ko": "나 곧 끝낼 거야.", "en": "I'm going to finish soon." }
      ]
    },
    {
      "day": 9, "verb": "go", "phase": "이동·만능", "ready": true, "title": "go · 방향",
      "concept": "go에 방향 단어를 붙여라. go up, go down, go out, go in, go back. 그리고 Let's go 가자. 물속에서 쓸 말이 거의 다 여기 있어 — 내려가, 올라가, 천천히 가.",
      "items": [
        { "id": "d9_01", "tag": "go", "ko": "올라가.", "en": "Go up." },
        { "id": "d9_02", "tag": "go", "ko": "내려가.", "en": "Go down." },
        { "id": "d9_03", "tag": "go", "ko": "나가.", "en": "Go out." },
        { "id": "d9_04", "tag": "go", "ko": "들어가.", "en": "Go in." },
        { "id": "d9_05", "tag": "go", "ko": "돌아가.", "en": "Go back." },
        { "id": "d9_06", "tag": "go", "ko": "계속 가.", "en": "Keep going." },
        { "id": "d9_07", "tag": "go", "ko": "저리 가.", "en": "Go away." },
        { "id": "d9_08", "tag": "go", "ko": "천천히 가.", "en": "Go slow." },
        { "id": "d9_09", "tag": "go", "ko": "먼저 가.", "en": "Go ahead." },
        { "id": "d9_10", "tag": "go", "ko": "직진해.", "en": "Go straight." },
        { "id": "d9_11", "tag": "go", "ko": "우리 올라가.", "en": "We're going up." },
        { "id": "d9_12", "tag": "go", "ko": "나 밖에 나가.", "en": "I'm going out." },
        { "id": "d9_13", "tag": "go", "ko": "다시 들어가.", "en": "Go back in." },
        { "id": "d9_14", "tag": "go", "ko": "더 깊이 가지 마.", "en": "Don't go deeper." },
        { "id": "d9_15", "tag": "go", "ko": "가자.", "en": "Let's go." },
        { "id": "d9_16", "tag": "go", "ko": "너 먼저 가.", "en": "You go first." },
        { "id": "d9_17", "tag": "go", "ko": "위로 천천히 올라가.", "en": "Go up slowly." },
        { "id": "d9_18", "tag": "go", "ko": "왼쪽으로 가.", "en": "Go left." },
        { "id": "d9_19", "tag": "go", "ko": "오른쪽으로 가.", "en": "Go right." },
        { "id": "d9_20", "tag": "go", "ko": "끝까지 가.", "en": "Go all the way." }
      ]
    },
    {
      "day": 10, "verb": "get", "phase": "이동·만능", "ready": true, "title": "get · 받다·얻다",
      "concept": "get은 영어의 왕이야. 먼저 얻다·받다·사다. I got it. Where did you get it? 가게에서 Can I get a coffee? 하면 커피 하나 주세요가 돼. 어려운 단어 대신 get 하나.",
      "items": [
        { "id": "d10_01", "tag": "get", "ko": "알았어.", "en": "I got it." },
        { "id": "d10_02", "tag": "get", "ko": "나 커피 사 올 거야.", "en": "I'm going to get a coffee." },
        { "id": "d10_03", "tag": "get", "ko": "커피 하나 주세요.", "en": "Can I get a coffee?" },
        { "id": "d10_04", "tag": "get", "ko": "너 그거 어디서 샀어?", "en": "Where did you get it?" },
        { "id": "d10_05", "tag": "get", "ko": "나 택시 잡을 거야.", "en": "I'm going to get a taxi." },
        { "id": "d10_06", "tag": "get", "ko": "나 표 구했어.", "en": "I got a ticket." },
        { "id": "d10_07", "tag": "get", "ko": "물 좀 주세요.", "en": "Can I get some water?" },
        { "id": "d10_08", "tag": "get", "ko": "나 새 폰 샀어.", "en": "I got a new phone." },
        { "id": "d10_09", "tag": "get", "ko": "너 선물 받았어?", "en": "Did you get a gift?" },
        { "id": "d10_10", "tag": "get", "ko": "나 네 문자 받았어.", "en": "I got your text." },
        { "id": "d10_11", "tag": "get", "ko": "도움 좀 받아.", "en": "Get some help." },
        { "id": "d10_12", "tag": "get", "ko": "나 그거 못 샀어.", "en": "I didn't get it." },
        { "id": "d10_13", "tag": "get", "ko": "영수증 좀 주세요.", "en": "Can I get the receipt?" },
        { "id": "d10_14", "tag": "get", "ko": "나 일자리 구했어.", "en": "I got a job." },
        { "id": "d10_15", "tag": "get", "ko": "너 그거 받았어?", "en": "Did you get it?" },
        { "id": "d10_16", "tag": "get", "ko": "메뉴판 좀 주세요.", "en": "Can I get a menu?" },
        { "id": "d10_17", "tag": "get", "ko": "나 좋은 자리 잡았어.", "en": "I got a good seat." },
        { "id": "d10_18", "tag": "get", "ko": "나 차 한 대 빌릴 거야.", "en": "I'm going to get a car." },
        { "id": "d10_19", "tag": "get", "ko": "뭐 갖다 드릴까요?", "en": "What can I get you?" },
        { "id": "d10_20", "tag": "get", "ko": "나 방금 알았어.", "en": "I just got it." }
      ]
    },
    {
      "day": 11, "verb": "get", "phase": "이동·만능", "ready": true, "title": "get · 되다·도착하다",
      "concept": "같은 get이 ~되다와 도착하다도 돼. get tired 피곤해지다, It's getting cold 추워지고 있다, I got home 집에 도착했다. 변화와 도착을 한 동사로.",
      "items": [
        { "id": "d11_01", "tag": "get", "ko": "나 피곤해졌어.", "en": "I got tired." },
        { "id": "d11_02", "tag": "get", "ko": "나 집에 도착했어.", "en": "I got home." },
        { "id": "d11_03", "tag": "get", "ko": "너 언제 도착해?", "en": "When do you get there?" },
        { "id": "d11_04", "tag": "get", "ko": "추워지고 있어.", "en": "It's getting cold." },
        { "id": "d11_05", "tag": "get", "ko": "나 배고파지고 있어.", "en": "I'm getting hungry." },
        { "id": "d11_06", "tag": "get", "ko": "우리 거의 다 왔어.", "en": "We're getting there." },
        { "id": "d11_07", "tag": "get", "ko": "늦어지고 있어.", "en": "It's getting late." },
        { "id": "d11_08", "tag": "get", "ko": "어두워지고 있어.", "en": "It's getting dark." },
        { "id": "d11_09", "tag": "get", "ko": "나 좋아지고 있어.", "en": "I'm getting better." },
        { "id": "d11_10", "tag": "get", "ko": "너 거기 어떻게 가?", "en": "How do you get there?" },
        { "id": "d11_11", "tag": "get", "ko": "나 직장에 도착했어.", "en": "I got to work." },
        { "id": "d11_12", "tag": "get", "ko": "더워지고 있어.", "en": "It's getting hot." },
        { "id": "d11_13", "tag": "get", "ko": "나 긴장돼.", "en": "I'm getting nervous." },
        { "id": "d11_14", "tag": "get", "ko": "나 익숙해지고 있어.", "en": "I'm getting used to it." },
        { "id": "d11_15", "tag": "get", "ko": "나 거기 못 갔어.", "en": "I didn't get there." },
        { "id": "d11_16", "tag": "get", "ko": "나 졸려.", "en": "I'm getting sleepy." },
        { "id": "d11_17", "tag": "get", "ko": "너 잘 도착했어?", "en": "Did you get there okay?" },
        { "id": "d11_18", "tag": "get", "ko": "점점 쉬워지고 있어.", "en": "It's getting easier." },
        { "id": "d11_19", "tag": "get", "ko": "나 짜증나.", "en": "I'm getting annoyed." },
        { "id": "d11_20", "tag": "get", "ko": "곧 어두워질 거야.", "en": "It's going to get dark soon." }
      ]
    },
    {
      "day": 12, "verb": "get", "phase": "이동·만능", "ready": true, "title": "get · 이해하다 + 구동사",
      "concept": "get은 이해하다이기도 해. I get it 이해했어. 그리고 방향을 붙이면 get up 일어나, get in 타, get out 내려/나와, get on/off 타다/내리다. 먹다처럼 하나로 여러 개야.",
      "items": [
        { "id": "d12_01", "tag": "get", "ko": "이해했어.", "en": "I get it." },
        { "id": "d12_02", "tag": "get", "ko": "이해 안 돼.", "en": "I don't get it." },
        { "id": "d12_03", "tag": "get", "ko": "너 이해돼?", "en": "Do you get it?" },
        { "id": "d12_04", "tag": "get", "ko": "일어나.", "en": "Get up." },
        { "id": "d12_05", "tag": "get", "ko": "나 일찍 일어나.", "en": "I get up early." },
        { "id": "d12_06", "tag": "get", "ko": "타.", "en": "Get in." },
        { "id": "d12_07", "tag": "get", "ko": "나와.", "en": "Get out." },
        { "id": "d12_08", "tag": "get", "ko": "차에 타.", "en": "Get in the car." },
        { "id": "d12_09", "tag": "get", "ko": "차에서 내려.", "en": "Get out of the car." },
        { "id": "d12_10", "tag": "get", "ko": "버스에 타.", "en": "Get on the bus." },
        { "id": "d12_11", "tag": "get", "ko": "버스에서 내려.", "en": "Get off the bus." },
        { "id": "d12_12", "tag": "get", "ko": "물에서 나와.", "en": "Get out of the water." },
        { "id": "d12_13", "tag": "get", "ko": "비켜.", "en": "Get out of the way." },
        { "id": "d12_14", "tag": "get", "ko": "좀 쉬어.", "en": "Get some rest." },
        { "id": "d12_15", "tag": "get", "ko": "빨리 나아.", "en": "Get well soon." },
        { "id": "d12_16", "tag": "get", "ko": "준비해.", "en": "Get ready." },
        { "id": "d12_17", "tag": "get", "ko": "가까이 붙어.", "en": "Get close." },
        { "id": "d12_18", "tag": "get", "ko": "나 이제 이해돼.", "en": "Now I get it." },
        { "id": "d12_19", "tag": "get", "ko": "내 말 이해돼?", "en": "Do you get what I mean?" },
        { "id": "d12_20", "tag": "get", "ko": "어서 타.", "en": "Get in, quick." }
      ]
    },
    {
      "day": 13, "verb": "복습", "phase": "이동·만능", "ready": true, "title": "복습 · go+get",
      "concept": "오늘은 go와 get을 섞는다. 두 만능동사만으로 이동하고, 사고, 도착하고, 이해하는 걸 다 말해보자.",
      "items": [
        { "id": "d13_01", "tag": "mix", "ko": "나 집에 가, 피곤해.", "en": "I'm going home. I'm tired." },
        { "id": "d13_02", "tag": "mix", "ko": "나 커피 사러 가.", "en": "I'm going to get a coffee." },
        { "id": "d13_03", "tag": "mix", "ko": "우리 늦었어, 택시 잡자.", "en": "We're late. Let's get a taxi." },
        { "id": "d13_04", "tag": "mix", "ko": "내려가, 천천히.", "en": "Go down, slowly." },
        { "id": "d13_05", "tag": "mix", "ko": "너 거기 어떻게 가?", "en": "How do you get there?" },
        { "id": "d13_06", "tag": "mix", "ko": "차에 타, 가자.", "en": "Get in. Let's go." },
        { "id": "d13_07", "tag": "mix", "ko": "나 거의 다 왔어.", "en": "I'm almost there." },
        { "id": "d13_08", "tag": "mix", "ko": "어두워지고 있어, 나가자.", "en": "It's getting dark. Let's go out." },
        { "id": "d13_09", "tag": "mix", "ko": "너 그거 샀어?", "en": "Did you get it?" },
        { "id": "d13_10", "tag": "mix", "ko": "나 안 가, 피곤해지고 있어.", "en": "I'm not going. I'm getting tired." },
        { "id": "d13_11", "tag": "mix", "ko": "위로 천천히 올라가.", "en": "Go up slowly." },
        { "id": "d13_12", "tag": "mix", "ko": "물에서 나와, 추워.", "en": "Get out of the water. It's cold." },
        { "id": "d13_13", "tag": "mix", "ko": "너 일어났어?", "en": "Did you get up?" },
        { "id": "d13_14", "tag": "mix", "ko": "나 일하러 가는 중이야.", "en": "I'm going to work." },
        { "id": "d13_15", "tag": "mix", "ko": "메뉴 좀 주세요.", "en": "Can I get a menu?" },
        { "id": "d13_16", "tag": "mix", "ko": "우리 거의 다 왔어.", "en": "We're getting there." },
        { "id": "d13_17", "tag": "mix", "ko": "돌아가, 길 잘못 들었어.", "en": "Go back. It's the wrong way." },
        { "id": "d13_18", "tag": "mix", "ko": "나 이해돼, 가자.", "en": "I get it. Let's go." },
        { "id": "d13_19", "tag": "mix", "ko": "버스 타, 시내 가.", "en": "Get on the bus. It goes downtown." },
        { "id": "d13_20", "tag": "mix", "ko": "너 준비됐어? 가자.", "en": "Are you ready? Let's go." }
      ]
    },
    {
      "day": 14, "verb": "want", "phase": "욕구·능력·허락", "ready": true, "title": "want · ~하고 싶어",
      "concept": "want는 원해. want 뒤에 명사면 그걸 원하는 거고, want to 뒤에 동사면 그걸 하고 싶은 거야. I want water. I want to go. 욕구는 전부 이 하나로.",
      "items": [
        { "id": "d14_01", "tag": "want", "ko": "나 물 줘.", "en": "I want water." },
        { "id": "d14_02", "tag": "want", "ko": "너 뭐 원해?", "en": "What do you want?" },
        { "id": "d14_03", "tag": "want", "ko": "나 커피 마시고 싶어.", "en": "I want a coffee." },
        { "id": "d14_04", "tag": "want", "ko": "나 가고 싶어.", "en": "I want to go." },
        { "id": "d14_05", "tag": "want", "ko": "나 집에 가고 싶어.", "en": "I want to go home." },
        { "id": "d14_06", "tag": "want", "ko": "너 가고 싶어?", "en": "Do you want to go?" },
        { "id": "d14_07", "tag": "want", "ko": "나 자고 싶어.", "en": "I want to sleep." },
        { "id": "d14_08", "tag": "want", "ko": "나 이거 원해.", "en": "I want this." },
        { "id": "d14_09", "tag": "want", "ko": "나 그거 안 원해.", "en": "I don't want that." },
        { "id": "d14_10", "tag": "want", "ko": "나 쉬고 싶어.", "en": "I want to rest." },
        { "id": "d14_11", "tag": "want", "ko": "너 뭐 먹고 싶어?", "en": "What do you want to eat?" },
        { "id": "d14_12", "tag": "want", "ko": "나 너랑 가고 싶어.", "en": "I want to go with you." },
        { "id": "d14_13", "tag": "want", "ko": "나 더 원해.", "en": "I want more." },
        { "id": "d14_14", "tag": "want", "ko": "나 지금 가고 싶어.", "en": "I want to go now." },
        { "id": "d14_15", "tag": "want", "ko": "너 마실 거 원해?", "en": "Do you want a drink?" },
        { "id": "d14_16", "tag": "want", "ko": "나 다이빙하고 싶어.", "en": "I want to dive." },
        { "id": "d14_17", "tag": "want", "ko": "나 안 가고 싶어.", "en": "I don't want to go." },
        { "id": "d14_18", "tag": "want", "ko": "나 집에 있고 싶어.", "en": "I want to stay home." },
        { "id": "d14_19", "tag": "want", "ko": "너 뭐 하고 싶어?", "en": "What do you want to do?" },
        { "id": "d14_20", "tag": "want", "ko": "나 그냥 쉬고 싶어.", "en": "I just want to rest." }
      ]
    },
    {
      "day": 15, "verb": "can", "phase": "욕구·능력·허락", "ready": true, "title": "can · 할 수 있어",
      "concept": "can은 할 수 있어, 그리고 부탁과 허락. I can do it. Can you help me? Can I...? 물속 비상에서 I can't breathe 숨 못 쉬겠어 같은 결정적인 말도 여기서 나와.",
      "items": [
        { "id": "d15_01", "tag": "can", "ko": "나 할 수 있어.", "en": "I can do it." },
        { "id": "d15_02", "tag": "can", "ko": "나 못 해.", "en": "I can't do it." },
        { "id": "d15_03", "tag": "can", "ko": "너 할 수 있어?", "en": "Can you do it?" },
        { "id": "d15_04", "tag": "can", "ko": "나 도와줄 수 있어.", "en": "I can help you." },
        { "id": "d15_05", "tag": "can", "ko": "도와줄래?", "en": "Can you help me?" },
        { "id": "d15_06", "tag": "can", "ko": "나 영어 할 줄 알아.", "en": "I can speak English." },
        { "id": "d15_07", "tag": "can", "ko": "나 영어 잘 못해.", "en": "I can't speak English well." },
        { "id": "d15_08", "tag": "can", "ko": "이거 가져도 돼요?", "en": "Can I have this?" },
        { "id": "d15_09", "tag": "can", "ko": "화장실 써도 돼요?", "en": "Can I use the bathroom?" },
        { "id": "d15_10", "tag": "can", "ko": "천천히 말해 줄래요?", "en": "Can you speak slowly?" },
        { "id": "d15_11", "tag": "can", "ko": "나 수영할 수 있어.", "en": "I can swim." },
        { "id": "d15_12", "tag": "can", "ko": "나 안 보여.", "en": "I can't see." },
        { "id": "d15_13", "tag": "can", "ko": "나 보여?", "en": "Can you see me?" },
        { "id": "d15_14", "tag": "can", "ko": "나 숨 못 쉬겠어.", "en": "I can't breathe." },
        { "id": "d15_15", "tag": "can", "ko": "다시 말해 줄래요?", "en": "Can you say that again?" },
        { "id": "d15_16", "tag": "can", "ko": "나 기다릴 수 있어.", "en": "I can wait." },
        { "id": "d15_17", "tag": "can", "ko": "우리 지금 갈 수 있어?", "en": "Can we go now?" },
        { "id": "d15_18", "tag": "can", "ko": "나 안 들려.", "en": "I can't hear you." },
        { "id": "d15_19", "tag": "can", "ko": "나 운전할 수 있어.", "en": "I can drive." },
        { "id": "d15_20", "tag": "can", "ko": "너 이거 고칠 수 있어?", "en": "Can you fix this?" }
      ]
    },
    {
      "day": 16, "verb": "need", "phase": "욕구·능력·허락", "ready": true, "title": "need · 필요해",
      "concept": "need는 필요해. need 뒤에 명사면 그게 필요한 거, need to 뒤에 동사면 그걸 해야 하는 거. I need air. I need to rest. 다이빙에서 가장 중요한 말들이야.",
      "items": [
        { "id": "d16_01", "tag": "need", "ko": "나 도움 필요해.", "en": "I need help." },
        { "id": "d16_02", "tag": "need", "ko": "나 물 필요해.", "en": "I need water." },
        { "id": "d16_03", "tag": "need", "ko": "나 공기 필요해.", "en": "I need air." },
        { "id": "d16_04", "tag": "need", "ko": "너 뭐 필요해?", "en": "What do you need?" },
        { "id": "d16_05", "tag": "need", "ko": "나 쉬어야 해.", "en": "I need to rest." },
        { "id": "d16_06", "tag": "need", "ko": "나 가야 해.", "en": "I need to go." },
        { "id": "d16_07", "tag": "need", "ko": "나 자야 해.", "en": "I need to sleep." },
        { "id": "d16_08", "tag": "need", "ko": "나 이거 필요해.", "en": "I need this." },
        { "id": "d16_09", "tag": "need", "ko": "나 그거 필요 없어.", "en": "I don't need that." },
        { "id": "d16_10", "tag": "need", "ko": "나 의사 필요해.", "en": "I need a doctor." },
        { "id": "d16_11", "tag": "need", "ko": "나 시간이 좀 필요해.", "en": "I need some time." },
        { "id": "d16_12", "tag": "need", "ko": "너 도움 필요해?", "en": "Do you need help?" },
        { "id": "d16_13", "tag": "need", "ko": "나 화장실 가야 해.", "en": "I need a bathroom." },
        { "id": "d16_14", "tag": "need", "ko": "나 좀 멈춰야 해.", "en": "I need to stop." },
        { "id": "d16_15", "tag": "need", "ko": "나 네 도움이 필요해.", "en": "I need your help." },
        { "id": "d16_16", "tag": "need", "ko": "나 새 거 필요해.", "en": "I need a new one." },
        { "id": "d16_17", "tag": "need", "ko": "우리 더 천천히 가야 해.", "en": "We need to slow down." },
        { "id": "d16_18", "tag": "need", "ko": "나 먹어야 해.", "en": "I need to eat." },
        { "id": "d16_19", "tag": "need", "ko": "너 그거 필요해?", "en": "Do you need it?" },
        { "id": "d16_20", "tag": "need", "ko": "나 지금 가야 해.", "en": "I need to go now." }
      ]
    },
    {
      "day": 17, "verb": "let", "phase": "욕구·능력·허락", "ready": true, "title": "let · let me / let's",
      "concept": "let은 부드럽게 말하는 마법의 단어. Let me는 내가 할게 또는 하게 해줘, Let's는 같이 하자. Let me see. Let's go. 명령 대신 이걸 쓰면 훨씬 자연스러워.",
      "items": [
        { "id": "d17_01", "tag": "let", "ko": "어디 보자.", "en": "Let me see." },
        { "id": "d17_02", "tag": "let", "ko": "생각 좀 해볼게.", "en": "Let me think." },
        { "id": "d17_03", "tag": "let", "ko": "내가 도와줄게.", "en": "Let me help you." },
        { "id": "d17_04", "tag": "let", "ko": "가자.", "en": "Let's go." },
        { "id": "d17_05", "tag": "let", "ko": "먹자.", "en": "Let's eat." },
        { "id": "d17_06", "tag": "let", "ko": "시작하자.", "en": "Let's start." },
        { "id": "d17_07", "tag": "let", "ko": "알려줘.", "en": "Let me know." },
        { "id": "d17_08", "tag": "let", "ko": "내가 할게.", "en": "Let me do it." },
        { "id": "d17_09", "tag": "let", "ko": "들어가자.", "en": "Let's go in." },
        { "id": "d17_10", "tag": "let", "ko": "잠깐 쉬자.", "en": "Let's rest." },
        { "id": "d17_11", "tag": "let", "ko": "내가 확인해볼게.", "en": "Let me check." },
        { "id": "d17_12", "tag": "let", "ko": "천천히 하자.", "en": "Let's slow down." },
        { "id": "d17_13", "tag": "let", "ko": "기다리자.", "en": "Let's wait." },
        { "id": "d17_14", "tag": "let", "ko": "내가 물어볼게.", "en": "Let me ask." },
        { "id": "d17_15", "tag": "let", "ko": "그거 내가 가져갈게.", "en": "Let me get it." },
        { "id": "d17_16", "tag": "let", "ko": "다시 해보자.", "en": "Let's try again." },
        { "id": "d17_17", "tag": "let", "ko": "그만하자.", "en": "Let's stop." },
        { "id": "d17_18", "tag": "let", "ko": "같이 가자.", "en": "Let's go together." },
        { "id": "d17_19", "tag": "let", "ko": "내가 보여줄게.", "en": "Let me show you." },
        { "id": "d17_20", "tag": "let", "ko": "올라가자.", "en": "Let's go up." }
      ]
    },
    {
      "day": 18, "verb": "복습", "phase": "욕구·능력·허락", "ready": true, "title": "복습 · want+can+need+let",
      "concept": "오늘은 want·can·need·let을 섞는다. 원하고, 할 수 있고, 필요하고, 같이 하자고 — 네 동사면 욕구와 부탁이 다 돼. 물속 상황도 미리 한번.",
      "items": [
        { "id": "d18_01", "tag": "mix", "ko": "나 쉬고 싶어, 좀 쉬자.", "en": "I want to rest. Let's take a break." },
        { "id": "d18_02", "tag": "mix", "ko": "나 도움 필요해, 도와줄래?", "en": "I need help. Can you help me?" },
        { "id": "d18_03", "tag": "mix", "ko": "나 가고 싶은데 못 가.", "en": "I want to go, but I can't." },
        { "id": "d18_04", "tag": "mix", "ko": "천천히 하자, 나 못 따라가.", "en": "Let's slow down. I can't keep up." },
        { "id": "d18_05", "tag": "mix", "ko": "너 뭐 필요해?", "en": "What do you need?" },
        { "id": "d18_06", "tag": "mix", "ko": "나 물 마시고 싶어.", "en": "I want some water." },
        { "id": "d18_07", "tag": "mix", "ko": "나 안 보여, 너 보여?", "en": "I can't see. Can you see?" },
        { "id": "d18_08", "tag": "mix", "ko": "가자, 준비됐어.", "en": "Let's go. I'm ready." },
        { "id": "d18_09", "tag": "mix", "ko": "나 숨 못 쉬겠어, 올라가자.", "en": "I can't breathe. Let's go up." },
        { "id": "d18_10", "tag": "mix", "ko": "나 좀 멈춰야 해.", "en": "I need to stop." },
        { "id": "d18_11", "tag": "mix", "ko": "내가 도와줄게, 기다려.", "en": "Let me help. Wait." },
        { "id": "d18_12", "tag": "mix", "ko": "나 다이빙하고 싶어.", "en": "I want to dive." },
        { "id": "d18_13", "tag": "mix", "ko": "너 갈 수 있어?", "en": "Can you go?" },
        { "id": "d18_14", "tag": "mix", "ko": "나 공기 필요해.", "en": "I need air." },
        { "id": "d18_15", "tag": "mix", "ko": "생각 좀 해볼게.", "en": "Let me think." },
        { "id": "d18_16", "tag": "mix", "ko": "나 안 가고 싶어, 피곤해.", "en": "I don't want to go. I'm tired." },
        { "id": "d18_17", "tag": "mix", "ko": "다시 해보자.", "en": "Let's try again." },
        { "id": "d18_18", "tag": "mix", "ko": "너 이거 고칠 수 있어?", "en": "Can you fix this?" },
        { "id": "d18_19", "tag": "mix", "ko": "나 의사 필요해.", "en": "I need a doctor." },
        { "id": "d18_20", "tag": "mix", "ko": "가자, 늦었어.", "en": "Let's go. We're late." }
      ]
    },
    {
      "day": 19, "verb": "take", "phase": "액션·종합", "ready": true, "title": "take · 가져가다·~하다",
      "concept": "take는 가져가다지만 그 이상이야. take a look 한번 보다, take the bus 버스 타다, take a photo 사진 찍다, take time 시간 걸리다, take a deep breath 깊게 숨 쉬다. 또 하나의 만능동사.",
      "items": [
        { "id": "d19_01", "tag": "take", "ko": "이거 가져.", "en": "Take it." },
        { "id": "d19_02", "tag": "take", "ko": "이거 가져가.", "en": "Take this." },
        { "id": "d19_03", "tag": "take", "ko": "한번 봐.", "en": "Take a look." },
        { "id": "d19_04", "tag": "take", "ko": "사진 찍어 줄래요?", "en": "Can you take a photo?" },
        { "id": "d19_05", "tag": "take", "ko": "나 사진 찍을게.", "en": "I'm going to take a photo." },
        { "id": "d19_06", "tag": "take", "ko": "버스 타.", "en": "Take the bus." },
        { "id": "d19_07", "tag": "take", "ko": "나 택시 탈 거야.", "en": "I'm going to take a taxi." },
        { "id": "d19_08", "tag": "take", "ko": "시간 좀 걸려.", "en": "It takes time." },
        { "id": "d19_09", "tag": "take", "ko": "얼마나 걸려요?", "en": "How long does it take?" },
        { "id": "d19_10", "tag": "take", "ko": "약 먹어.", "en": "Take your medicine." },
        { "id": "d19_11", "tag": "take", "ko": "좀 쉬어.", "en": "Take a break." },
        { "id": "d19_12", "tag": "take", "ko": "숨 깊게 쉬어.", "en": "Take a deep breath." },
        { "id": "d19_13", "tag": "take", "ko": "나 좀 데려가 줘.", "en": "Take me with you." },
        { "id": "d19_14", "tag": "take", "ko": "공항으로 데려다주세요.", "en": "Take me to the airport." },
        { "id": "d19_15", "tag": "take", "ko": "자리에 앉아.", "en": "Take a seat." },
        { "id": "d19_16", "tag": "take", "ko": "천천히 해.", "en": "Take your time." },
        { "id": "d19_17", "tag": "take", "ko": "이 길로 가.", "en": "Take this road." },
        { "id": "d19_18", "tag": "take", "ko": "우산 가져가.", "en": "Take an umbrella." },
        { "id": "d19_19", "tag": "take", "ko": "나 샤워할 거야.", "en": "I'm going to take a shower." },
        { "id": "d19_20", "tag": "take", "ko": "이걸로 할게요.", "en": "I'll take this one." }
      ]
    },
    {
      "day": 20, "verb": "make", "phase": "액션·종합", "ready": true, "title": "make · 만들다·~되게",
      "concept": "make는 만들다, 그리고 ~되게 하다. make it 해내다 또는 시간 맞춰 가다, make sure 확실히 하다, that makes sense 말 되네. 만들고 ~되게 하는 걸 한 동사로.",
      "items": [
        { "id": "d20_01", "tag": "make", "ko": "나 해냈어.", "en": "I made it." },
        { "id": "d20_02", "tag": "make", "ko": "너 해낼 수 있어.", "en": "You can make it." },
        { "id": "d20_03", "tag": "make", "ko": "우리 시간 맞춰 갈 수 있어.", "en": "We can make it." },
        { "id": "d20_04", "tag": "make", "ko": "확실히 해.", "en": "Make sure." },
        { "id": "d20_05", "tag": "make", "ko": "문 잠겼는지 확인해.", "en": "Make sure the door is locked." },
        { "id": "d20_06", "tag": "make", "ko": "나 마음 정했어.", "en": "I made a decision." },
        { "id": "d20_07", "tag": "make", "ko": "나 실수했어.", "en": "I made a mistake." },
        { "id": "d20_08", "tag": "make", "ko": "나 저녁 만들 거야.", "en": "I'm going to make dinner." },
        { "id": "d20_09", "tag": "make", "ko": "커피 좀 타 줄래?", "en": "Can you make some coffee?" },
        { "id": "d20_10", "tag": "make", "ko": "그거 말 되네.", "en": "That makes sense." },
        { "id": "d20_11", "tag": "make", "ko": "그거 말 안 돼.", "en": "That doesn't make sense." },
        { "id": "d20_12", "tag": "make", "ko": "나 친구 사귀었어.", "en": "I made a friend." },
        { "id": "d20_13", "tag": "make", "ko": "빨리 하자.", "en": "Let's make it quick." },
        { "id": "d20_14", "tag": "make", "ko": "나 예약했어.", "en": "I made a reservation." },
        { "id": "d20_15", "tag": "make", "ko": "그게 날 행복하게 해.", "en": "It makes me happy." },
        { "id": "d20_16", "tag": "make", "ko": "소음 내지 마.", "en": "Don't make noise." },
        { "id": "d20_17", "tag": "make", "ko": "계획 세우자.", "en": "Let's make a plan." },
        { "id": "d20_18", "tag": "make", "ko": "나 돈 좀 벌어.", "en": "I make some money." },
        { "id": "d20_19", "tag": "make", "ko": "안전한지 확실히 해.", "en": "Make sure it's safe." },
        { "id": "d20_20", "tag": "make", "ko": "너 해낼 거야.", "en": "You're going to make it." }
      ]
    },
    {
      "day": 21, "verb": "wh", "phase": "액션·종합", "ready": true, "title": "육하원칙 · 질문 자유자재",
      "concept": "오늘은 육하원칙. who 누구, what 뭐, when 언제, where 어디, why 왜, how 어떻게. 이 여섯 단어를 문장 앞에 놓으면 무엇이든 물어볼 수 있어. 여행에서 제일 많이 쓸 무기야.",
      "items": [
        { "id": "d21_01", "tag": "wh", "ko": "이게 뭐야?", "en": "What is this?" },
        { "id": "d21_02", "tag": "wh", "ko": "너 누구야?", "en": "Who are you?" },
        { "id": "d21_03", "tag": "wh", "ko": "그거 언제야?", "en": "When is it?" },
        { "id": "d21_04", "tag": "wh", "ko": "화장실 어디예요?", "en": "Where is the bathroom?" },
        { "id": "d21_05", "tag": "wh", "ko": "왜?", "en": "Why?" },
        { "id": "d21_06", "tag": "wh", "ko": "이거 어떻게 해요?", "en": "How do you do this?" },
        { "id": "d21_07", "tag": "wh", "ko": "너 뭐 해?", "en": "What are you doing?" },
        { "id": "d21_08", "tag": "wh", "ko": "그 사람 누구야?", "en": "Who is he?" },
        { "id": "d21_09", "tag": "wh", "ko": "우리 언제 가?", "en": "When do we go?" },
        { "id": "d21_10", "tag": "wh", "ko": "너 어디 가?", "en": "Where are you going?" },
        { "id": "d21_11", "tag": "wh", "ko": "왜 안 돼?", "en": "Why not?" },
        { "id": "d21_12", "tag": "wh", "ko": "얼마예요?", "en": "How much is it?" },
        { "id": "d21_13", "tag": "wh", "ko": "몇 시예요?", "en": "What time is it?" },
        { "id": "d21_14", "tag": "wh", "ko": "누가 알아?", "en": "Who knows?" },
        { "id": "d21_15", "tag": "wh", "ko": "이거 누구 거예요?", "en": "Whose is this?" },
        { "id": "d21_16", "tag": "wh", "ko": "거기 어떻게 가요?", "en": "How do I get there?" },
        { "id": "d21_17", "tag": "wh", "ko": "얼마나 걸려요?", "en": "How long does it take?" },
        { "id": "d21_18", "tag": "wh", "ko": "너 뭐 원해?", "en": "What do you want?" },
        { "id": "d21_19", "tag": "wh", "ko": "왜 늦었어?", "en": "Why are you late?" },
        { "id": "d21_20", "tag": "wh", "ko": "어느 거예요?", "en": "Which one?" }
      ]
    },
    {
      "day": 22, "verb": "복습", "phase": "액션·종합", "ready": true, "title": "종합 · 짧은 대화",
      "concept": "오늘은 종합. 지금까지 배운 핵심동사 전부를 짧은 대화로 엮는다. 만나서 인사하고, 묻고, 부탁하고, 헤어지는 한 흐름이야.",
      "items": [
        { "id": "d22_01", "tag": "mix", "ko": "안녕, 잘 지내?", "en": "Hi, how are you?" },
        { "id": "d22_02", "tag": "mix", "ko": "나 잘 지내, 너는?", "en": "I'm good. How about you?" },
        { "id": "d22_03", "tag": "mix", "ko": "어디 가?", "en": "Where are you going?" },
        { "id": "d22_04", "tag": "mix", "ko": "나 일하러 가.", "en": "I'm going to work." },
        { "id": "d22_05", "tag": "mix", "ko": "너 시간 있어?", "en": "Do you have time?" },
        { "id": "d22_06", "tag": "mix", "ko": "미안, 나 가야 해.", "en": "Sorry, I have to go." },
        { "id": "d22_07", "tag": "mix", "ko": "뭐 좀 먹을래?", "en": "Do you want to get something to eat?" },
        { "id": "d22_08", "tag": "mix", "ko": "그래, 배고파.", "en": "Yes, I'm hungry." },
        { "id": "d22_09", "tag": "mix", "ko": "뭐 먹고 싶어?", "en": "What do you want to eat?" },
        { "id": "d22_10", "tag": "mix", "ko": "아무거나 괜찮아.", "en": "Anything is okay." },
        { "id": "d22_11", "tag": "mix", "ko": "이거 얼마예요?", "en": "How much is this?" },
        { "id": "d22_12", "tag": "mix", "ko": "카드 돼요?", "en": "Can I use a card?" },
        { "id": "d22_13", "tag": "mix", "ko": "화장실 어디예요?", "en": "Where is the bathroom?" },
        { "id": "d22_14", "tag": "mix", "ko": "천천히 말해 줄래요?", "en": "Can you speak slowly?" },
        { "id": "d22_15", "tag": "mix", "ko": "다시 말해 줄래요?", "en": "Can you say that again?" },
        { "id": "d22_16", "tag": "mix", "ko": "나 영어 잘 못해.", "en": "I can't speak English well." },
        { "id": "d22_17", "tag": "mix", "ko": "도와주실 수 있어요?", "en": "Can you help me?" },
        { "id": "d22_18", "tag": "mix", "ko": "고마워요.", "en": "Thank you." },
        { "id": "d22_19", "tag": "mix", "ko": "천만에요.", "en": "You're welcome." },
        { "id": "d22_20", "tag": "mix", "ko": "또 봐.", "en": "See you." }
      ]
    },
    {
      "day": 23, "verb": "trip", "phase": "칸쿤 실전", "ready": true, "title": "공항·입국",
      "concept": "이제 칸쿤 실전. 공항과 입국. 전부 지금까지 배운 핵심동사로 돼 — I'm here for diving. I have a reservation. Where is...? 새 단어 거의 없어.",
      "items": [
        { "id": "d23_01", "tag": "trip", "ko": "안녕하세요.", "en": "Hello." },
        { "id": "d23_02", "tag": "trip", "ko": "여기 여권 있어요.", "en": "Here is my passport." },
        { "id": "d23_03", "tag": "trip", "ko": "저 다이빙하러 왔어요.", "en": "I'm here for diving." },
        { "id": "d23_04", "tag": "trip", "ko": "저 휴가차 왔어요.", "en": "I'm here on vacation." },
        { "id": "d23_05", "tag": "trip", "ko": "2주 있을 거예요.", "en": "I'm going to stay for two weeks." },
        { "id": "d23_06", "tag": "trip", "ko": "호텔 예약했어요.", "en": "I have a hotel reservation." },
        { "id": "d23_07", "tag": "trip", "ko": "짐 찾는 곳 어디예요?", "en": "Where is baggage claim?" },
        { "id": "d23_08", "tag": "trip", "ko": "제 가방을 못 찾겠어요.", "en": "I can't find my bag." },
        { "id": "d23_09", "tag": "trip", "ko": "택시 어디서 타요?", "en": "Where can I get a taxi?" },
        { "id": "d23_10", "tag": "trip", "ko": "시내까지 얼마예요?", "en": "How much is it to downtown?" },
        { "id": "d23_11", "tag": "trip", "ko": "이거 호텔 주소예요.", "en": "Here is the hotel address." },
        { "id": "d23_12", "tag": "trip", "ko": "와이파이 있어요?", "en": "Do you have wifi?" },
        { "id": "d23_13", "tag": "trip", "ko": "환전 어디서 해요?", "en": "Where can I get cash?" },
        { "id": "d23_14", "tag": "trip", "ko": "도와주실 수 있어요?", "en": "Can you help me?" },
        { "id": "d23_15", "tag": "trip", "ko": "영어 하세요?", "en": "Do you speak English?" },
        { "id": "d23_16", "tag": "trip", "ko": "천천히 말해 주세요.", "en": "Please speak slowly." },
        { "id": "d23_17", "tag": "trip", "ko": "화장실 어디예요?", "en": "Where is the bathroom?" },
        { "id": "d23_18", "tag": "trip", "ko": "제 비행기 늦었어요.", "en": "My flight is late." },
        { "id": "d23_19", "tag": "trip", "ko": "출구 어디예요?", "en": "Where is the exit?" },
        { "id": "d23_20", "tag": "trip", "ko": "고맙습니다.", "en": "Thank you." }
      ]
    },
    {
      "day": 24, "verb": "trip", "phase": "칸쿤 실전", "ready": true, "title": "다이빙샵·장비",
      "concept": "다이빙샵에서. 장비 빌리고, 물어보고, 준비하는 말. I need a tank. Can I get...? I'm a certified diver. 역시 핵심동사로 다 돼.",
      "items": [
        { "id": "d24_01", "tag": "trip", "ko": "저 다이빙하러 왔어요.", "en": "I'm here to dive." },
        { "id": "d24_02", "tag": "trip", "ko": "저 자격증 있어요.", "en": "I'm a certified diver." },
        { "id": "d24_03", "tag": "trip", "ko": "예약했어요.", "en": "I have a reservation." },
        { "id": "d24_04", "tag": "trip", "ko": "공기통 필요해요.", "en": "I need a tank." },
        { "id": "d24_05", "tag": "trip", "ko": "장비 빌릴 수 있어요?", "en": "Can I rent some gear?" },
        { "id": "d24_06", "tag": "trip", "ko": "이거 제 사이즈예요?", "en": "Is this my size?" },
        { "id": "d24_07", "tag": "trip", "ko": "웻수트 필요해요.", "en": "I need a wetsuit." },
        { "id": "d24_08", "tag": "trip", "ko": "이거 어떻게 써요?", "en": "How do you use this?" },
        { "id": "d24_09", "tag": "trip", "ko": "물 차가워요?", "en": "Is the water cold?" },
        { "id": "d24_10", "tag": "trip", "ko": "얼마나 깊어요?", "en": "How deep is it?" },
        { "id": "d24_11", "tag": "trip", "ko": "가이드 있어요?", "en": "Do you have a guide?" },
        { "id": "d24_12", "tag": "trip", "ko": "저 동굴 다이빙해요.", "en": "I'm doing cave diving." },
        { "id": "d24_13", "tag": "trip", "ko": "몇 시에 가요?", "en": "What time do we go?" },
        { "id": "d24_14", "tag": "trip", "ko": "얼마나 걸려요?", "en": "How long does it take?" },
        { "id": "d24_15", "tag": "trip", "ko": "이거 안전해요?", "en": "Is it safe?" },
        { "id": "d24_16", "tag": "trip", "ko": "제 공기통 확인해 주세요.", "en": "Can you check my tank?" },
        { "id": "d24_17", "tag": "trip", "ko": "저 좀 천천히 가야 해요.", "en": "I need to go slow." },
        { "id": "d24_18", "tag": "trip", "ko": "제 짝이 누구예요?", "en": "Who is my buddy?" },
        { "id": "d24_19", "tag": "trip", "ko": "준비됐어요.", "en": "I'm ready." },
        { "id": "d24_20", "tag": "trip", "ko": "가요.", "en": "Let's go." }
      ]
    },
    {
      "day": 25, "verb": "trip", "phase": "칸쿤 실전", "ready": true, "title": "물속 소통",
      "concept": "물속 소통. 여기가 이 모든 공부의 증거야 — 생사가 걸린 소통이 핵심동사와 방향 단어만으로 다 돼. I'm okay. Go down. Come up. Slow down. Let's go.",
      "items": [
        { "id": "d25_01", "tag": "trip", "ko": "나 괜찮아.", "en": "I'm okay." },
        { "id": "d25_02", "tag": "trip", "ko": "너 괜찮아?", "en": "Are you okay?" },
        { "id": "d25_03", "tag": "trip", "ko": "내려가.", "en": "Go down." },
        { "id": "d25_04", "tag": "trip", "ko": "올라가.", "en": "Go up." },
        { "id": "d25_05", "tag": "trip", "ko": "천천히.", "en": "Slow down." },
        { "id": "d25_06", "tag": "trip", "ko": "멈춰.", "en": "Stop." },
        { "id": "d25_07", "tag": "trip", "ko": "가자.", "en": "Let's go." },
        { "id": "d25_08", "tag": "trip", "ko": "따라와.", "en": "Follow me." },
        { "id": "d25_09", "tag": "trip", "ko": "가까이 붙어.", "en": "Stay close." },
        { "id": "d25_10", "tag": "trip", "ko": "내 손 잡아.", "en": "Take my hand." },
        { "id": "d25_11", "tag": "trip", "ko": "나 공기 부족해.", "en": "I'm low on air." },
        { "id": "d25_12", "tag": "trip", "ko": "나 숨 못 쉬겠어.", "en": "I can't breathe." },
        { "id": "d25_13", "tag": "trip", "ko": "너 보여.", "en": "I can see you." },
        { "id": "d25_14", "tag": "trip", "ko": "나 안 보여.", "en": "I can't see." },
        { "id": "d25_15", "tag": "trip", "ko": "위로 올라가자.", "en": "Let's go up." },
        { "id": "d25_16", "tag": "trip", "ko": "여기서 기다려.", "en": "Wait here." },
        { "id": "d25_17", "tag": "trip", "ko": "안 괜찮아.", "en": "I'm not okay." },
        { "id": "d25_18", "tag": "trip", "ko": "도와줘.", "en": "Help me." },
        { "id": "d25_19", "tag": "trip", "ko": "이쪽으로.", "en": "This way." },
        { "id": "d25_20", "tag": "trip", "ko": "다 됐어, 돌아가자.", "en": "We're done. Let's go back." }
      ]
    },
    {
      "day": 26, "verb": "trip", "phase": "칸쿤 실전", "ready": true, "title": "식당·비상·작별",
      "concept": "마지막 날. 식당에서 주문하고 계산하고, 아프면 도움을 청하고, 고맙다고 인사하는 말. Can I get the check? I don't feel good. Thank you. 여기까지면 칸쿤에서 산다.",
      "items": [
        { "id": "d26_01", "tag": "trip", "ko": "메뉴 좀 주세요.", "en": "Can I get a menu?" },
        { "id": "d26_02", "tag": "trip", "ko": "이거 주세요.", "en": "Can I get this?" },
        { "id": "d26_03", "tag": "trip", "ko": "물 좀 주세요.", "en": "Can I get some water?" },
        { "id": "d26_04", "tag": "trip", "ko": "이거 맛있어요.", "en": "This is good." },
        { "id": "d26_05", "tag": "trip", "ko": "계산서 주세요.", "en": "Can I get the check?" },
        { "id": "d26_06", "tag": "trip", "ko": "카드 돼요?", "en": "Can I use a card?" },
        { "id": "d26_07", "tag": "trip", "ko": "화장실 어디예요?", "en": "Where is the bathroom?" },
        { "id": "d26_08", "tag": "trip", "ko": "저 몸이 안 좋아요.", "en": "I don't feel good." },
        { "id": "d26_09", "tag": "trip", "ko": "의사 필요해요.", "en": "I need a doctor." },
        { "id": "d26_10", "tag": "trip", "ko": "도와주세요.", "en": "Help me, please." },
        { "id": "d26_11", "tag": "trip", "ko": "이거 안 시켰어요.", "en": "I didn't order this." },
        { "id": "d26_12", "tag": "trip", "ko": "얼마예요?", "en": "How much is it?" },
        { "id": "d26_13", "tag": "trip", "ko": "정말 맛있었어요.", "en": "It was really good." },
        { "id": "d26_14", "tag": "trip", "ko": "너무 매워요.", "en": "It's too spicy." },
        { "id": "d26_15", "tag": "trip", "ko": "하나 더 주세요.", "en": "Can I get one more?" },
        { "id": "d26_16", "tag": "trip", "ko": "포장돼요?", "en": "Can I get this to go?" },
        { "id": "d26_17", "tag": "trip", "ko": "고마워요.", "en": "Thank you." },
        { "id": "d26_18", "tag": "trip", "ko": "정말 좋았어요.", "en": "It was great." },
        { "id": "d26_19", "tag": "trip", "ko": "또 올게요.", "en": "I'll come back." },
        { "id": "d26_20", "tag": "trip", "ko": "잘 지내요.", "en": "Take care." }
      ]
    }
  ]
};
